CREATE TABLE account_tokens (
    token TEXT NOT NULL UNIQUE,
    account_id BIGINT NOT NULL REFERENCES account,
    expire TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP + INTERVAL '1 hour',
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);